### PR TITLE
[PHO-442] Feature/sdk cleanup

### PR DESCRIPTION
**Pull request by HarrisonHough**
## Description

-   This PR removes everything that is no longer needed for the new strategy. It removes scripts, samples and other things such as 
          - asset api requests & models (it does keep the asset data structure though as that can be used as part of CharacterData stored on a loaded model which might be useful in future
          - Character create, update and preview requests and models
          - All samples have been removed 
          - Cache generator window and most cache classes are removed. 
          - CharacterLoader cleanup (removed unused functions)
   

## How to Test

-   Test that main flows work. Including dev window stuff (login, logout loading blueprint etc)
- using CharacterApi.LoadAsync to load a nextgen avatar by id at runtime EG 
```cs
public class TestScript : MonoBehaviour
{
    [SerializeField]
    private string avatarId;
    
    private CharacterLoader characterLoader;
    
    private async Task Start()
    {
        characterLoader = new CharacterLoader();
        
        Thread.Sleep(500);
        var character = await characterLoader.LoadAsync(avatarId);
        Debug.Log($"Character Loaded {character.name}");
    }
}
```

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.

[PHO-442]: https://ready-player-me.atlassian.net/browse/PHO-442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rk132** [comment]
image
Clear these as well ⬆️

**Comment by HarrisonHough** [comment]
> image Clear these as well ⬆️

ahh nice catch! forgot about that, will update

**Comment by HarrisonHough** [comment]
samples shouldn't show now in package manager

**Comment by MaxAndreassenRPM** [comment]
Looks good to me, and template loading still works both with and without a tag passed in 💹

**Review by MaxAndreassenRPM — APPROVED** [review]

**Pull request merged**
