### PR TITLE
[PHO-443] Feature/templates refactor

### PR DESCRIPTION
**Pull request by HarrisonHough**
## Description

image

-   RPM dev window updated
     - The template creator ui stuff from before has been removed. 
     - The skeleton definition field has been removed from the UI (functionality however is still there)
     - a new DefaultTemplatePrefab has been added (this will be the default prefab that a character will load for a specific blueprint ID 
     - When you login the first time it will create a CharacterTemplateConfig using the Application ID for the unique name and auto populate it (which also downloads the .glbs to use as initial prefabs) 
     - If a config already exists for an application it will not overwrite existing settings
     - In the window if you reassign the Default Template Prefab it should update it on the CharacterTemplateConfig scriptable object, putting the latest selected one to index 0 on the prefab list 
     
     
image

- updated character template object names and class structure 
     - Each template will basically map to a Blueprint (using blueprint ID) and the template can have multiple prefabs with tags that can be used for filtering same way as previous filtering worked

## How to Test

-   Install the plugin from this branch 
```
https://github.com/readyplayerme/rpm-unity-next-gen-sdk.git#feature/templates-refactor
```
- open the dev window by going to Tools > Ready Player Me
- Then login either with demo or with your account
- First time login will be a bit slow loading the blueprints because of the time it takes to download all the blueprint .glbs
- Second time login will be faster as it will just read from the existing config 
- try assigning objects to the Default Template Prefab and cehck that it updates in the CharacterTemplateConfig with the matching app ID as the file name 

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.

[PHO-443]: https://ready-player-me.atlassian.net/browse/PHO-443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by HarrisonHough** [comment]
I know we discussed hiding the ID property of the templates but I think it's not a good idea. Because if we don't allow it to be editable then it's not possible for them to add new templates, since we create it for them only the first time they login (because we didn't want to overwrite their settings each time). 
Maybe we can rethink it a bit, at the very least we could just make it so that if we detect a new blueprint that's not there it will be added to the array and leave the others. Although that also brings up the question of whether we need to also remove a template if it was removed from studio

**Comment by MaxAndreassenRPM** [comment]
> I know we discussed hiding the ID property of the templates but I think it's not a good idea. Because if we don't allow it to be editable then it's not possible for them to add new templates, since we create it for them only the first time they login (because we didn't want to overwrite their settings each time). Maybe we can rethink it a bit, at the very least we could just make it so that if we detect a new blueprint that's not in the config it will be added to the array and leave the others. Although that also brings up the question of whether we need to also remove a template if it was removed from studio.

Happy to leave it there for now, especially since we've added the 'default template' input field still, so you don't have to edit or touch the ID unless you really want to. We can discuss again in the future if it becomes an issue.

**Comment by HarrisonHough** [comment]
> > I know we discussed hiding the ID property of the templates but I think it's not a good idea. Because if we don't allow it to be editable then it's not possible for them to add new templates, since we create it for them only the first time they login (because we didn't want to overwrite their settings each time). Maybe we can rethink it a bit, at the very least we could just make it so that if we detect a new blueprint that's not in the config it will be added to the array and leave the others. Although that also brings up the question of whether we need to also remove a template if it was removed from studio.
> 
> Happy to leave it there for now, especially since we've added the 'default template' input field still, so you don't have to edit or touch the ID unless you really want to. We can discuss again in the future if it becomes an issue.

yeah the main point I was getting at is that with it hidden or not settable you are basically stuck with what you get unless you delete and reopen the editor window (triggering it to create again). Or you edit the scriptable object asset file manually in an IDE
I might be overthinking it though :D

**Comment by HarrisonHough** [comment]
But overall it should be visible I think (not necessarily editable) because othewise it becomes confusing which blueprint you are mapping it too.

**Review by MaxAndreassenRPM — APPROVED** [review]
Works great and is much simpler! Awesome job.

**Pull request closed without merging**
